all:
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    lb1:
      ansible_host: 192.168.1.182
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
    app1:
      ansible_host: 192.168.1.181
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
    db1:
      ansible_host: 192.168.1.180
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
  vars:
    versions:
      awx: 9.3.0
      postgres: 10
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    # awx
    kubernetes_deployment_name: awx
    kubernetes_namespace: awx
    web_mem_request: 1
    web_cpu_request: 500
    task_mem_request: 2
    task_cpu_request: 1500
    rabbitmq_mem_request: 2
    rabbitmq_cpu_request: 500
    memcached_hostname: localhost
    memcached_mem_request: 1
    memcached_cpu_request: 500
    insights_url_base: "https://example.org"
    automation_analytics_url: "https://example.org"
    insights_agent_mime: "application/example"
    container_groups_image: "ansible/ansible-runner"
    secret_key: "{{ lookup('community.general.random_string', length=20, special=false) }}"
    rabbitmq_user: 'awx'
    rabbitmq_password: "{{ lookup('community.general.random_string', length=20, special=false) }}"
    rabbitmq_erlang_cookie: "{{ lookup('community.general.random_string', length=20, special=false) }}"
    ca_trust_bundle: "/etc/pki/tls/certs/ca-bundle.crt"
    pg_database: "{{ hostvars['db1']['ansible_default_ipv4']['address'] }}"
    pg_username: awx
    pg_password: "{{ lookup('community.general.random_string', length=20, special=false) }}"
    pg_port: 5432
    kubernetes_statefulset_api_version: apps/v1
    kubernetes_task_version: "{{ versions.awx }}"
    kubernetes_task_image: ansible/awx_task
    kubernetes_web_version: "{{ versions.awx }}"
    kubernetes_web_image: ansible/awx_web
    kubernetes_rabbitmq_version: "3.7.21"
    kubernetes_rabbitmq_image: "ansible/awx_rabbitmq"
    kubernetes_memcached_version: "latest"
    kubernetes_memcached_image: "memcached"
  children:
    k3s:
      hosts:
        app1:
    postgres:
      hosts:
        db1:
