all:
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    lb1:
      ansible_host: 192.168.1.85
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
    app1:
      ansible_host: 192.168.1.114
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
    db1:
      ansible_host: 192.168.1.102
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
  vars:
    versions:
      awx: 9.3.0
      postgres: 10
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kubernetes_context: default
    # awx
    kubernetes_deployment_name: awx
    kubernetes_namespace: awx
    web_mem_request: 1
    web_cpu_request: 500
    task_mem_request: 1
    task_cpu_request: 1000
    rabbitmq_mem_request: 1
    rabbitmq_cpu_request: 500
    memcached_hostname: localhost
    memcached_mem_request: 1
    memcached_cpu_request: 500
    insights_url_base: "https://example.org"
    automation_analytics_url: "https://example.org"
    insights_agent_mime: "application/example"
    container_groups_image: "ansible/ansible-runner"
    secret_key: hunter2
    rabbitmq_user: 'awx'
    rabbitmq_password: hunter2
    rabbitmq_erlang_cookie: hunter2
    ca_trust_bundle: "/etc/pki/tls/certs/ca-bundle.crt"
    pg_hostname: "{{ hostvars['db1']['ansible_default_ipv4']['address'] }}"
    pg_database: awx
    pg_username: awx
    pg_password: hunter2
    pg_port: 5432
    kubernetes_statefulset_api_version: apps/v1
    kubernetes_task_version: "{{ versions.awx }}"
    kubernetes_task_image: ansible/awx_task
    kubernetes_web_version: "{{ versions.awx }}"
    kubernetes_web_image: ansible/awx_web
    kubernetes_rabbitmq_version: "3.7.21"
    kubernetes_rabbitmq_image: "ansible/awx_rabbitmq"
    kubernetes_memcached_version: "latest"
    kubernetes_memcached_image: "memcached"
    kubectl_or_oc: /snap/bin/kubectl
    management_cpu_limit: 1000
    management_mem_limit: 1
    admin_user: admin
    admin_password: hunter2
    admin_email: admin@example.com
    deployment_object: sts
    replicas: 1
  children:
    k3s:
      hosts:
        app1:
    postgres:
      hosts:
        db1:
