- name: install python3-pip
  ansible.builtin.apt:
    state: present
    name: python3-pip
    update_cache: true
  become: true

- name: install pypi things
  ansible.builtin.pip:
    state: present
    name:
      - openshift==0.11.0
      - kubernetes-validate
  become: true

- name: install kubectl
  community.general.snap:
    state: present
    name: kubectl
    classic: true
  become: true

- name: create awx namespace
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ kubernetes_namespace }}"
    api_version: v1
    kind: Namespace
  become: true

- name: deploy awx manifests
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition: "{{ lookup('ansible.builtin.template', versions.awx ~ '/' ~ item ~ '.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: true
      strict: true
  loop:
    - configmap
    - secret
    - serviceaccount
    - service
    - configmap2
    - role
    - rolebinding
    - statefulset
    - configmap3
    - service2
    - service3
    - ingress
