- name: reload postgres
  ansible.builtin.systemd:
    name: postgresql
    state: reloaded
  become: true

- name: restart postgres
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
  become: true
