---

- name: facts
  hosts: all
  gather_facts: true
  become: false
  tasks:
    - name: setup
      ansible.builtin.setup:
      tags: ['always']

- name: ubuntu
  hosts: ubuntu
  gather_facts: true
  become: false
  tasks:
    - name: ubuntu
      ansible.builtin.include_role:
        name: ubuntu
        tasks_from: main.yml
        apply:
          tags: ['ubuntu']
      tags: ['ubuntu']

- name: k3s
  hosts: k3s
  gather_facts: true
  become: false
  tasks:
    - name: k3s
      ansible.builtin.include_role:
        name: k3s
        tasks_from: main.yml

- name: postgres
  hosts: postgres
  gather_facts: true
  become: false
  tasks:
    - name: postgres
      ansible.builtin.include_role:
        name: postgres
        tasks_from: main.yml
        apply:
          tags: ['postgres']
      tags: ['postgres']

- name: awx
  hosts: k3s
  gather_facts: false
  become: false
  tasks:
    - name: awx
      ansible.builtin.include_role:
        name: awx
        tasks_from: main.yml
        apply:
          tags: ['awx']
      tags: ['awx']
